/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["selector", '[data-theme="dark"]'],
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: "1.5rem",
        sm: "1.5rem",
        lg: "2rem",
      },
      screens: {
        "2xl": "1180px",
      },
    },
    extend: {
      colors: {
        background: "var(--bg)",
        "background-subtle": "var(--bg-2)",
        foreground: "var(--text)",
        muted: "var(--text-muted)",
        faint: "var(--text-faint)",
        border: "var(--border)",
        "border-strong": "var(--border-strong)",
        surface: "var(--surface)",
        "surface-subtle": "var(--surface-2)",
        brand: "var(--brand)",
        "brand-strong": "var(--brand-strong)",
        "brand-soft": "var(--brand-soft)",
        positive: "var(--pos, var(--chart-positive))",
        "positive-soft": "var(--pos-soft)",
        negative: "var(--neg, var(--chart-negative))",
        "negative-soft": "var(--neg-soft)",
        warning: "var(--warn)",
        "warning-soft": "var(--warn-soft)",
        "invert-bg": "var(--invert-bg)",
        "invert-bg-hover": "var(--invert-bg-hover)",
        "invert-text": "var(--invert-text)",
        "invert-border": "var(--invert-border)",
        ring: "var(--ring)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        "chart-label": "var(--chart-label)",
        "chart-foreground": "var(--chart-foreground)",
        "chart-foreground-muted": "var(--chart-foreground-muted)",
        dysm: "var(--dysm)",
        "dysm-soft": "var(--dysm-soft)",
        me: "var(--me)",
        "me-soft": "var(--me-soft)",
        spatial: "var(--spatial)",
        "spatial-soft": "var(--spatial-soft)",
        "page-accent": "var(--page-accent)",
        "page-accent-soft": "var(--page-accent-soft)",
        "page-accent-hero": "var(--page-accent-hero)",
        "page-accent-stat": "var(--page-accent-stat)",
        "page-accent-border": "var(--page-accent-border)",
        "page-accent-chip": "var(--page-accent-chip)",
        "page-accent-chip-border": "var(--page-accent-chip-border)",
        "page-accent-muted": "var(--page-accent-muted)",
      },
      fontFamily: {
        sans: ["var(--font)"],
        display: ["var(--display)"],
      },
      borderRadius: {
        DEFAULT: "var(--radius)",
        sm: "var(--radius-sm)",
        lg: "var(--radius-lg)",
      },
      maxWidth: {
        content: "1180px",
        copy: "68ch",
      },
    },
  },
  plugins: [],
};
