export const ui = {
  section: "[&>.container]:border-t [&>.container]:border-solid [&>.container]:border-border-strong [&>.container]:py-[76px] max-sm:[&>.container]:py-14",
  sectionTight: "[&>.container]:border-t [&>.container]:border-solid [&>.container]:border-border-strong [&>.container]:py-12 max-sm:[&>.container]:py-9",
  sectionFrame: "container !px-0 border-t border-solid border-border-strong",
  sectionBand: "border-b border-solid border-border-strong px-6 py-12 lg:px-8 lg:py-14",
  sectionBody: "px-6 py-10 lg:px-8 lg:py-12",
  sectionTag: "mb-3 text-xs font-semibold uppercase text-faint",
  heading1: "font-display text-4xl font-bold leading-tight max-sm:text-3xl",
  heading2: "font-display text-3xl font-bold leading-tight max-sm:text-2xl",
  heading3: "font-display text-lg font-bold leading-tight",
  lede: "text-lg leading-relaxed text-foreground",
  muted: "text-muted",
  small: "text-sm",
  field: "mb-4 flex flex-col gap-1.5 text-sm font-semibold text-foreground",
  input: "min-h-10 w-full min-w-0 border border-border-strong bg-surface px-3 py-2 text-sm font-normal text-foreground outline-none transition-colors placeholder:text-faint focus:border-brand focus:ring-2 focus:ring-brand-soft disabled:cursor-not-allowed disabled:opacity-60",
  textarea: "min-h-28 w-full min-w-0 resize-y border border-border-strong bg-surface px-3 py-2 text-sm font-normal leading-relaxed text-foreground outline-none transition-colors placeholder:text-faint focus:border-brand focus:ring-2 focus:ring-brand-soft disabled:cursor-not-allowed disabled:opacity-60",
  fieldError: "text-xs font-semibold text-negative",
  linkButton: "cursor-pointer border-0 bg-transparent p-0 text-left font-sans text-current underline hover:text-brand-strong disabled:cursor-not-allowed disabled:opacity-60",
  message: "mt-2 min-h-5 border border-border bg-surface-subtle px-3 py-2.5 text-sm leading-relaxed",
  messageError: "border-negative border-l-[3px] bg-negative-soft text-negative",
  messageSuccess: "border-positive border-l-[3px] bg-positive-soft text-positive",
  tableWrap: "w-full overflow-x-auto border border-border [-webkit-overflow-scrolling:touch]",
  table: "w-full min-w-[640px] border-collapse text-sm [&_th]:border-b [&_th]:border-border [&_th]:bg-surface-subtle [&_th]:px-4 [&_th]:py-3 [&_th]:text-left [&_th]:text-xs [&_th]:font-semibold [&_th]:uppercase [&_th]:text-faint [&_td]:border-b [&_td]:border-border [&_td]:px-4 [&_td]:py-3 [&_td]:text-left [&_tbody_tr:last-child_td]:border-b-0",
  tableNumber: "text-right tabular-nums",
  emptyRow: "py-12 text-center text-muted",
  badge: "inline-flex min-h-7 items-center border border-border bg-surface-subtle px-2.5 py-1 text-xs text-muted",
  badgePositive: "border-transparent bg-positive-soft text-positive",
  badgeNegative: "border-transparent bg-negative-soft text-negative",
  badgeMuted: "border-border bg-surface-subtle text-muted",
  iconButton: "grid size-10 cursor-pointer place-items-center border border-border-strong bg-surface text-foreground transition-colors hover:bg-surface-subtle focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand disabled:pointer-events-none disabled:opacity-60",
  modal: "fixed inset-0 z-[100] grid place-items-center p-5",
  modalBackdrop: "absolute inset-0 bg-black/60 backdrop-blur-sm",
  modalCard: "relative max-h-[90vh] w-full max-w-4xl overflow-auto border border-border bg-surface p-6 shadow-lg",
  panel: "border border-border bg-surface p-6",
  ruledGrid: "grid border-l border-t border-border",
  ruledCell: "min-w-0 border-b border-r border-border bg-surface p-6",
  kpiGrid: "my-4 flex flex-wrap border-l border-t border-border",
  kpi: "min-w-28 flex-1 border-b border-r border-border bg-surface-subtle px-4 py-3",
  kpiLabel: "text-xs font-semibold uppercase text-faint",
  kpiValue: "mt-0.5 font-display text-2xl font-bold tabular-nums",
};
